name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create google-services.json
      run: cat ./project/app/google-services.json | base64
    - name: Put data in google-services.json
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > ./project/app/google-services.json
    - name: Grant execute permission for gradlew
      working-directory: ./project
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./project
      run: ./gradlew build
    - name: Run Unit Tests
      working-directory: ./project
      run: ./gradlew test
